### ISSUE TITLE
Put DB config in separate file

### ISSUE THREAD

**Issue by martijnengler** [aaronpk/iMessage-Export#11]
I recently came across this project when I (finally) switched to Messages in iCloud, and wanted to backup before I clean up my Messages.

Had some fun with the SQL export, but since the config needs to be in `export-sql.php` you are either left with a "dirty" working dir (which is annoying for me, since I use git-remind), or you have to commit your database credentials; something I'd rather not do actually.

Simple solution would be to just put them in a separate config file. :)

Again, really appreciate the project!

**Comment by pocketarc** [comment]
@martijnengler Quick question - does switching to Messages in iCloud -stop- you from being able to back your chats up? It's the main thing stopping me from moving forward with the switch, and you seem to have first-hand experience now.

**Comment by martijnengler** [comment]
Nope, works fine. Coded/tested my PR *after* the switch. :-)

**Comment by pocketarc** [comment]
@martijnengler You're a god, thank you so much. It's literally the only reason I've been afraid to switch over, because I thought I would no longer be able to export my chats because they wouldn't be stored in the same format locally (I imagined).
